### ISSUE TITLE
Draft TAG work plan

### ISSUE THREAD

**Issue by ghwhitbread** [tdwg/tag#4]
* Coordinate review of the GUID Applicability Statements 
   - [ ] Deprecate LSID recommendation, 
   - [ ] Review all guid-as recomendadtions
   - [ ] Update/replace Statements for executive/membership review;
* Initiate review of the existing TDWG meta-model documentation  -> tdwg semantic model;
* Review the TDWG Technical "Road Map" and Best Practice documents

**Comment by baskaufs** [comment]
Out of date issue
